//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foxby.Core.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Foxby.Core.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] DocumentWithAddedParagraph {
            get {
                object obj = ResourceManager.GetObject("DocumentWithAddedParagraph", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DocumentWithAttribute {
            get {
                object obj = ResourceManager.GetObject("DocumentWithAttribute", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DocumentWithContentTypeTag {
            get {
                object obj = ResourceManager.GetObject("DocumentWithContentTypeTag", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DocumentWithHideContentInPlaceholderInTag {
            get {
                object obj = ResourceManager.GetObject("DocumentWithHideContentInPlaceholderInTag", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DocumentWithHideContentInTag {
            get {
                object obj = ResourceManager.GetObject("DocumentWithHideContentInTag", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DocumentWithoutAttributes {
            get {
                object obj = ResourceManager.GetObject("DocumentWithoutAttributes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DocumentWithoutParagraph {
            get {
                object obj = ResourceManager.GetObject("DocumentWithoutParagraph", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DocumentWithParagraph {
            get {
                object obj = ResourceManager.GetObject("DocumentWithParagraph", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DocumentWithReplacedTitle {
            get {
                object obj = ResourceManager.GetObject("DocumentWithReplacedTitle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DocumentWithTitle {
            get {
                object obj = ResourceManager.GetObject("DocumentWithTitle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DocumentWithTwoAttributes {
            get {
                object obj = ResourceManager.GetObject("DocumentWithTwoAttributes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DocumentWithVisibilityContentInPlaceholderInTag {
            get {
                object obj = ResourceManager.GetObject("DocumentWithVisibilityContentInPlaceholderInTag", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DocumentWithVisibilityContentInTag {
            get {
                object obj = ResourceManager.GetObject("DocumentWithVisibilityContentInTag", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] EmptyTemplate {
            get {
                object obj = ResourceManager.GetObject("EmptyTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] InvalidDocument {
            get {
                object obj = ResourceManager.GetObject("InvalidDocument", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Protected {
            get {
                object obj = ResourceManager.GetObject("Protected", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SdtElementWithoutSdtAlias {
            get {
                object obj = ResourceManager.GetObject("SdtElementWithoutSdtAlias", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] TableWithFormattedCells {
            get {
                object obj = ResourceManager.GetObject("TableWithFormattedCells", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Unprotected {
            get {
                object obj = ResourceManager.GetObject("Unprotected", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WithCellWithPlaceholder {
            get {
                object obj = ResourceManager.GetObject("WithCellWithPlaceholder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WithDifferentlyFormattedTextInPlaceholder {
            get {
                object obj = ResourceManager.GetObject("WithDifferentlyFormattedTextInPlaceholder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WithDifferentlyFormattedTextInTag {
            get {
                object obj = ResourceManager.GetObject("WithDifferentlyFormattedTextInTag", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WithIndentedOrderedListInserted {
            get {
                object obj = ResourceManager.GetObject("WithIndentedOrderedListInserted", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WithMainContentAndNewTag {
            get {
                object obj = ResourceManager.GetObject("WithMainContentAndNewTag", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WithMainContentAndThreeEmptyLines {
            get {
                object obj = ResourceManager.GetObject("WithMainContentAndThreeEmptyLines", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WithMainContentInserted {
            get {
                object obj = ResourceManager.GetObject("WithMainContentInserted", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WithMainContentInsertedJustifiedParagraphs {
            get {
                object obj = ResourceManager.GetObject("WithMainContentInsertedJustifiedParagraphs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WithMainContentInsertedMultilineParagraph {
            get {
                object obj = ResourceManager.GetObject("WithMainContentInsertedMultilineParagraph", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WithMainContentInsertedOrderedList {
            get {
                object obj = ResourceManager.GetObject("WithMainContentInsertedOrderedList", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WithMainContentInsertedTextWithSpaces {
            get {
                object obj = ResourceManager.GetObject("WithMainContentInsertedTextWithSpaces", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WithMainContentInsertedTwoParagraphs {
            get {
                object obj = ResourceManager.GetObject("WithMainContentInsertedTwoParagraphs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WithMainContentSingleTag {
            get {
                object obj = ResourceManager.GetObject("WithMainContentSingleTag", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WithMainContentTag {
            get {
                object obj = ResourceManager.GetObject("WithMainContentTag", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WithMainContentTwoDifferentParagraphs {
            get {
                object obj = ResourceManager.GetObject("WithMainContentTwoDifferentParagraphs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WithManyPlaceholders {
            get {
                object obj = ResourceManager.GetObject("WithManyPlaceholders", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WithManyPlaceholdersInsertedContent {
            get {
                object obj = ResourceManager.GetObject("WithManyPlaceholdersInsertedContent", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WithManyTags {
            get {
                object obj = ResourceManager.GetObject("WithManyTags", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WithManyTagsInsertedParagraph {
            get {
                object obj = ResourceManager.GetObject("WithManyTagsInsertedParagraph", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WithOrderedListWithParagraphs {
            get {
                object obj = ResourceManager.GetObject("WithOrderedListWithParagraphs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WithPlaceholderInPlaceholder {
            get {
                object obj = ResourceManager.GetObject("WithPlaceholderInPlaceholder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WithPlaceholderInsertedContentInserted {
            get {
                object obj = ResourceManager.GetObject("WithPlaceholderInsertedContentInserted", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WithPlaceholderInsertedInParagraph {
            get {
                object obj = ResourceManager.GetObject("WithPlaceholderInsertedInParagraph", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WithPlaceholderReplacedWithText {
            get {
                object obj = ResourceManager.GetObject("WithPlaceholderReplacedWithText", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WithPlaceholdersDenormalized {
            get {
                object obj = ResourceManager.GetObject("WithPlaceholdersDenormalized", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WithPlaceholdersNormalized {
            get {
                object obj = ResourceManager.GetObject("WithPlaceholdersNormalized", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WithSdtElements {
            get {
                object obj = ResourceManager.GetObject("WithSdtElements", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WithStyledInlineSdtElement {
            get {
                object obj = ResourceManager.GetObject("WithStyledInlineSdtElement", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WithStyledInlineSdtElementContentInserted {
            get {
                object obj = ResourceManager.GetObject("WithStyledInlineSdtElementContentInserted", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WithStyledSdtElements {
            get {
                object obj = ResourceManager.GetObject("WithStyledSdtElements", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WithStyledSdtElementsContentInserted {
            get {
                object obj = ResourceManager.GetObject("WithStyledSdtElementsContentInserted", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WithTableInsert {
            get {
                object obj = ResourceManager.GetObject("WithTableInsert", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WithTableWithMultilineCells {
            get {
                object obj = ResourceManager.GetObject("WithTableWithMultilineCells", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WithTableWithoutBordersInsert {
            get {
                object obj = ResourceManager.GetObject("WithTableWithoutBordersInsert", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WithTitlePlaceholder {
            get {
                object obj = ResourceManager.GetObject("WithTitlePlaceholder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WithTitlePlaceholderRemoved {
            get {
                object obj = ResourceManager.GetObject("WithTitlePlaceholderRemoved", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WithTitlePlaceholderReplaced {
            get {
                object obj = ResourceManager.GetObject("WithTitlePlaceholderReplaced", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WithTwoIndependentOrderedListsInserted {
            get {
                object obj = ResourceManager.GetObject("WithTwoIndependentOrderedListsInserted", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WithTwoParagraphsInBlockField {
            get {
                object obj = ResourceManager.GetObject("WithTwoParagraphsInBlockField", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WithTwoRunsInInlineField {
            get {
                object obj = ResourceManager.GetObject("WithTwoRunsInInlineField", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
